---
port_profiles:
  - profile: VLAN_10_PC
    vlans: 10
    mode: access
    port_channel:
      mode: active
    spanning_tree_portfast: edge

  - profile: VLAN_20_PC
    vlans: 20
    mode: access
    port_channel:
      mode: active
    spanning_tree_portfast: edge

  - profile: VLAN_30_PC
    vlans: 30
    mode: access
    port_channel:
      mode: active
    spanning_tree_portfast: edge

servers:
  - name: host1
    adapters:
      - switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [leaf1, leaf2]
        profile: VLAN_10_PC

  - name: host2
    adapters:
      - switch_ports: [ Ethernet9, Ethernet9 ]
        switches: [leaf1, leaf2]
        profile: VLAN_30_PC

  - name: host3
    adapters:
      - switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [leaf3, leaf4]
        profile: VLAN_20_PC


# network_ports:
#   - swithches: [leaf1, leaf2]
#     switch_ports: [Ethernet7, Ethernet7]
#     profile: VLAN_10_PC
#   - swithches: [leaf3, leaf4]
#     switch_ports: [Ethernet7, Ethernet7]
#     profile: VLAN_10_PC
