---

fabric_name: FABRIC

underlay_rfc5549: true

spine:
  defaults:
    bgp_as: 65100
    loopback_ipv4_pool: 192.168.101.0/24
    mlag: false
  nodes:
    - name: spine1
      id: 101 
    - name: spine2
      id: 102
    - name: spine3
      id: 103
    - name: spine4
      id: 104


l3leaf:
  defaults:
    bgp_as: 65101-65190
    loopback_ipv4_pool: 192.168.101.0/24
    vtep_loopback_ipv4_pool: 192.168.102.0/24
    uplink_switches: [spine1, spine2, spine3, spine4]
    uplink_interfaces: [Ethernet3, Ethernet4, Ethernet5, Ethernet6]
    uplink_ipv4_pool: 192.168.103.0/24
    mlag_interfaces: [Ethernet1, Ethernet2]
    mlag_peer_ipv4_pool: 10.255.252.0/24 # MLAG peer IPs
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24 # iBGP peering between MLAG peers
    virtual_router_mac_address: 02:1C:73:00:00:99
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    mlag: true
  node_groups:
    - group: mlag1
      nodes:
        - name: leaf1
          id: 11
          uplink_switch_interfaces: [Ethernet3, Ethernet3, Ethernet3, Ethernet3]
        - name: leaf2
          id: 12
          uplink_switch_interfaces: [Ethernet4, Ethernet4, Ethernet4, Ethernet4]
    - group: mlag2
      bgp_as: 65199
      nodes:
        - name: leaf3
          id: 13
          uplink_switch_interfaces: [Ethernet5, Ethernet5, Ethernet5, Ethernet5]
        - name: leaf4
          id: 14
          uplink_switch_interfaces: [Ethernet6, Ethernet6, Ethernet6, Ethernet6]

p2p_uplinks_mtu: 1550

bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

bgp_update_wait_install: false
bgp_update_wait_for_convergence: false

# Needed for Arista ATD Lab Environment
dns_domain: atd.lab
mgmt_interface: Management0
mgmt_interface_vrf: MGMT
mgmt_gateway: 192.168.0.1